name: Unity Project Build

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  uploadArtifactsAsPreRelease:
    name: Compress builds and upload the as draft pre-release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download OSX Artifact
        uses: actions/download-artifact@v4
        with:
          name: Build-StandaloneOSX
          path: StandaloneOSX

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: Build-StandaloneWindows64
          path: StandaloneWindows64

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: Build-StandaloneLinux64
          path: StandaloneLinux64

      - name: Zip
        run: |
              zip -r StandaloneOSX.zip StandaloneOSX
              zip -r StandaloneWindows64.zip StandaloneWindows64
              zip -r StandaloneLinux64.zip StandaloneLinux64

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0
          draft: true
          files: |
            StandaloneOSX.zip
            StandaloneWindows64.zip
            StandaloneLinux64.zip
